import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "@/provider/AppProvider";
import { Toaster } from "sonner";
import AuthProvider from "@/provider/AuthProvider";

export const metadata: Metadata = {
  title: "Tomato | Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AppProvider>
            {/* <Navbar /> */}
            <div className="">
              {children}
            </div>
            {/* <Footer /> */}
            <Toaster richColors position="bottom-right" /> 
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
