import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import AppProvider from "@/provider/AppProvider";
import { Toaster } from "sonner";
import AuthProvider from "@/provider/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AppProvider>
            <Navbar />
            <div className="mt-[88px]">
              {children}
            </div>
            <Footer />
            <Toaster richColors position="bottom-right" /> 
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
